#!/bin/bash

for version in 1.7.6 2.4.5 5.3.2 5.6.3
do
    sed -e "s/ES_VERSION/$version/" Dockerfile.es > Dockerfile.es.$version
done

for version in 6.3.2
do
    sed -e "s/ES_VERSION/$version/" Dockerfile2.es > Dockerfile.es.$version
done